/***** SURXONDARYO LIVE API v2 - FIXED
 * Google Form -> Google Sheets -> Apps Script -> Vercel -> HTML
 * Sheet A=timestamp, B onward=form fields.
 *****/
const SPREADSHEET_ID='1IyoVMJ98zSeHEYeCVmLEN7slOoroZ7tKpuZccVKUvKQ';
const SHEET_NAME='Ответы на форму (1)';
const DEFAULT_PAGE_SIZE=100,MAX_PAGE_SIZE=250;
const FIELD_KEYS=`tuman,mahalla,kocha,uy_raqami,boshliq_fio,tugilgan_sana,jinsi,telefon,malumoti,jami_aholi,erkaklar,ayollar,yosh_0_3,yosh_4_7,yosh_8_17,yosh_18_30,yosh_31_59,yosh_60_plus,vaqtincha_yashamaydigan,vaqtincha_sababi,oila_tarkibi,farzandlar_soni,ijtimoiy_himoyaga_muhtoj,muhtoj_soni,nogiron_shaxs,nogiron_bola,yolgiz_keksa,doimiy_parvarishga_muhtoj,ogir_kasal,ijtimoiy_reestr,nafaqa_beriladimi,nafaqa_turi,nafaqa_miqdori,mehnat_yoshidagilar,mehnat_ayollar,mehnat_erkaklar,rasmiy_ishlaydigan,norasmiy_ishlaydigan,mavsumiy_ishlaydigan,ozini_ozi_band,tadbirkorlik_bilan,xorijda_ishlaydigan,boshqa_hududda_ishlaydigan,ishsizlar,ishsiz_ayol,ishsiz_erkak,ishsiz_18_30,ishsiz_31_55,ishsiz_56_60,ishlash_istagi_bor,ishlash_istagi_yoq,istagi_yoqligi_sababi,doimiy_ishlash_istagi_bor,kasbiy_malakasi_bor,kasbiy_malakasi_yoq,qaysi_kasb_fio,asosiy_soha,qaysi_hudud_tayyor,min_oylik_kutilgan,jami_oylik_daromad,daromad_rasmiy,daromad_norasmiy,daromad_tadbirkorlik,daromad_tomorqa,daromad_chorvachilik,daromad_parrandachilik,daromad_xorij,daromad_pensiya,daromad_nafaqa,daromad_boshqa,jami_xarajat,xarajat_oziq_ovqat,xarajat_kommunal,xarajat_kredit,xarajat_talim,xarajat_dori,xarajat_transport,xarajat_boshqa,daromad_xarajatni_qoplaydimi,jon_boshiga_daromad,kredit_bor,kredit_qoldiq,kredit_oylik_tolov,kredit_muddat,kredit_kechikkan,yangi_kredit_ehtiyoji,kerakli_kredit_miqdori,kredit_maqsad,subsidiya_ehtiyoji,subsidiya_maqsad,tadbirkor_bor,faoliyat_turi,tadbirkorlik_daromad,kengaytirish_istagi,kengaytirish_mablag,asosiy_ehtiyoj_tadbirkorlik,kasb_hunar_ogrenish_istagi,qaysi_kasb_fio2,xorijiy_til_istagi,til_ingliz,til_rus,til_koreys,til_nemis,til_boshqa,maktabgacha_bolalar,maktab_yoshidagi_bolalar,maktabga_boradigan,maktabga_bormaydigan,ozlashtirishi_past,togarakka_qatnashadigan,qoshimcha_talim_ehtiyoji,bolalar_ehtiyoji,oliy_talim_olayotgan,doimiy_davolanuvchi,dori_ehtiyoji,nogiron_shaxs2,nogiron_bola2,tibbiy_korikka_muhtoj,davolanish_mablag_yetishmovchiligi,zarur_tibbiy_yordam,uyjoy_maydon,yashash_xonalari,uyjoy_yetarlimi,uyjoy_mulk_shakli,uyjoy_hujjatlari,tamir_tom,tamir_pol,tamir_shift,tamir_deraza,tamir_eshik,tamir_tandirxona,tamir_ochoqxona,tamir_devor,tamir_mablag,tabiiy_gaz,elektr,elektr_sarf,ichimlik_suvi,kanalizatsiya,isitish_tizimi,quyosh_paneli,internet,tex_xolodilnik,tex_televizor,tex_konditsioner,tex_kir_yuvish,tex_ariston,tex_kompyuter,tex_smartfon,tex_gaz_plita,tex_velosiped,tex_skuter,tex_avtomobil,tex_qishloq_texnika,tex_boshqa,tomorqa_maydon,tomorqa_bosh_maydon,tomorqadan_foydalanish,issiqxona_bor,issiqxona_maydon,sugorish_imkoniyati,chorva_qoramol,chorva_ot,chorva_qoy,chorva_echki,chorva_parranda,chorva_boshqa,chorvachilik_kengaytirish_istagi,kerakli_yordam,sport_shugullanuvchilar,sport_turi,sport_inshoot_ehtiyoji,yoshlar_asosiy_ehtiyoji,muammo_1,muammo_2,muammo_3,ehtiyoj_1,ehtiyoj_2,ehtiyoj_3,ijtimoiy_holat,iqtisodiy_holat,birinchi_navbat_masala`.split(',');
function sheet_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);return ss.getSheetByName(SHEET_NAME)||ss.getSheets()[0];}
function out_(o,e){const t=JSON.stringify(o),c=e&&e.parameter&&e.parameter.callback;if(c&&/^[A-Za-z_$][\w$\.]*$/.test(c))return ContentService.createTextOutput(c+'('+t+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(t).setMimeType(ContentService.MimeType.JSON);}
function num_(v){if(v===null||v===undefined||v==='')return 0;const m=String(v).replace(/\s/g,'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):0;}
function clean_(v){return String(v==null?'':v).trim();}
function yn_(v){const s=clean_(v).toLowerCase();if(!s)return'Noma\'lum';if(['ha','ҳа','yes','да'].indexOf(s)>=0)return'Ha';if(s.indexOf('qisman')>=0||s.indexOf('қисман')>=0)return'Qisman';if(['yoq',"yo'q",'йўқ','нет','no'].indexOf(s)>=0)return"Yo'q";return'Noma\'lum';}
function yes_(v){return yn_(v)==='Ha';}
function cacheGetJson_(k){try{const v=CacheService.getScriptCache().get(k);return v?JSON.parse(v):null;}catch(e){return null;}}
function cachePutJson_(k,o,s){try{CacheService.getScriptCache().put(k,JSON.stringify(o),s);}catch(e){}}
function add_(o,k,v){if(v)o[k]=(o[k]||0)+v;}
function count_(o,v){const k=yn_(v);o[k]=(o[k]||0)+1;}
function top_(o){return Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,12);}

function actionStats_(e){
 const p=e.parameter||{},f={tuman:clean_(p.tuman),mahalla:clean_(p.mahalla),kocha:clean_(p.kocha)};
 const key='stats:v6:'+JSON.stringify(f),old=cacheGetJson_(key);if(old)return old;
 const sh=sheet_(),n=Math.max(0,sh.getLastRow()-1);
 if(!n)return{ok:true,agg:{n:0,population:0,mehnatYosh:0,ishsizlar:0},geo:{rows:[]},coverage:[],filters:f,generatedAt:new Date().toISOString()};
 // Field number + 1 = Sheet column because column A is timestamp.
 const loc=sh.getRange(2,2,n,3).getDisplayValues();       // 1-3
 const dem=sh.getRange(2,11,n,9).getDisplayValues();     // 10-18
 const soc=sh.getRange(2,24,n,8).getDisplayValues();     // 23-30
 const emp=sh.getRange(2,35,n,22).getDisplayValues();    // 34-55
 const inc=sh.getRange(2,58,n,38).getDisplayValues();    // 57-94
 const house=sh.getRange(2,121,n,14).getDisplayValues(); // 121-134
 const util=sh.getRange(2,135,n,8).getDisplayValues();   // 135-142
 const apps=sh.getRange(2,143,n,13).getDisplayValues();  // 143-155
 const agri=sh.getRange(2,156,n,14).getDisplayValues();  // 156-169
 const issues=sh.getRange(2,170,n,13).getDisplayValues();// 170-182
 const familyType=sh.getRange(2,22,n,1).getDisplayValues();// field 21
 const education=sh.getRange(2,10,n,1).getDisplayValues();// field 9
 const a={n:0,population:0,men:0,women:0,mehnatYosh:0,ishsizlar:0,nogironShaxs:0,nogironBola:0,yolgizKeksa:0,expenseTotal:0,incomeTotal:0,yangiKreditEhtiyoji:0,subsidiyaEhtiyoji:0,tadbirkorBor:0,kengaytirishIstagi:0,kasbHunarIstagi:0};
 const incomeDist={},employment={},ageBands={'0–3':0,'4–7':0,'8–17':0,'18–30':0,'31–59':0,'60+':0},ijtimoiyReestr={},nafaqa={},kreditBor={},malumoti={},oilaTarkibi={},mulkShakli={},uyjoyYetarli={},uyjoyHujjatlari={},internet={},tabiiyGaz={},ichimlikSuvi={},elektr={},appliances={},livestock={},topP={},topN={},geo={};
 const names=['Xolodilnik','Televizor','Konditsioner','Kir yuvish','Ariston','Kompyuter','Smartfon','Gaz plita','Velosiped','Skuter','Avtomobil','Qishloq texnika'];
 for(let i=0;i<n;i++){
  const t=clean_(loc[i][0]),m=clean_(loc[i][1]),ko=clean_(loc[i][2]);if(!t)continue;if(f.tuman&&t!==f.tuman)continue;if(f.mahalla&&m!==f.mahalla)continue;if(f.kocha&&ko!==f.kocha)continue;
  const d=dem[i],s=soc[i],ep=emp[i],v=inc[i],h=house[i],u=util[i],ap=apps[i],la=agri[i],q=issues[i];
  a.n++;a.population+=num_(d[0]);a.men+=num_(d[1]);a.women+=num_(d[2]);a.mehnatYosh+=num_(ep[0]);a.ishsizlar+=num_(ep[10]);a.nogironShaxs+=num_(s[2]);a.nogironBola+=num_(s[3]);a.yolgizKeksa+=num_(s[4]);a.incomeTotal+=num_(v[3]);a.expenseTotal+=num_(v[14]);
  if(yn_(v[26])==='Ha')a.yangiKreditEhtiyoji++;if(yn_(v[29])==='Ha')a.subsidiyaEhtiyoji++;if(yn_(v[31])==='Ha')a.tadbirkorBor++;if(yn_(v[34])==='Ha')a.kengaytirishIstagi++;if(yn_(v[36])==='Ha')a.kasbHunarIstagi++;
  const g=geo[t]||(geo[t]={key:t,tuman:t,families:0,population:0,ishsizlar:0,mfy:{}});g.families++;g.population+=num_(d[0]);g.ishsizlar+=num_(ep[10]);if(m)g.mfy[m]=1;
  const money=num_(v[3]),band=money<=0?'Ma’lumot mavjud':money<=1000000?'1 mln gacha':money<=3000000?'1–3 mln':money<=5000000?'3–5 mln':money<=10000000?'5–10 mln':'10 mln+';add_(incomeDist,band,1);
  [['Rasmiy',ep[3]],['Norasmiy',ep[4]],['Mavsumiy',ep[5]],['O‘zini o‘zi band',ep[6]],['Tadbirkorlik',ep[7]],['Xorijda',ep[8]],['Boshqa hududda',ep[9]],['Ishsiz',ep[10]]].forEach(x=>add_(employment,x[0],num_(x[1])));
  [['0–3',d[3]],['4–7',d[4]],['8–17',d[5]],['18–30',d[6]],['31–59',d[7]],['60+',d[8]]].forEach(x=>add_(ageBands,x[0],num_(x[1])));
  count_(ijtimoiyReestr,s[7]);count_(nafaqa,ep[0]);count_(kreditBor,v[21]);count_(uyjoyYetarli,h[2]);count_(tabiiyGaz,u[0]);count_(elektr,u[1]);count_(ichimlikSuvi,u[3]);count_(internet,u[7]);
  if(h[3])add_(mulkShakli,clean_(h[3]),1);if(h[4])add_(uyjoyHujjatlari,clean_(h[4]),1);if(education[i][0])add_(malumoti,clean_(education[i][0]),1);if(familyType[i][0])add_(oilaTarkibi,clean_(familyType[i][0]),1);
  for(let j=0;j<12;j++)if(yes_(ap[j]))add_(appliances,names[j],1);
  for(let j=0;j<6;j++)add_(livestock,['Qoramol','Ot','Qo‘y','Echki','Parranda','Boshqa'][j],num_(la[6+j]));
  for(let j=0;j<3;j++){if(q[4+j])add_(topP,clean_(q[4+j]),1);if(q[7+j])add_(topN,clean_(q[7+j]),1);}
 }
 const geoRows=Object.values(geo).map(x=>({key:x.key,tuman:x.tuman,families:x.families,population:x.population,ishsizlar:x.ishsizlar,mfyCount:Object.keys(x.mfy).length})).sort((a,b)=>b.families-a.families);
 const coverage=geoRows.map(x=>({tuman:x.tuman,families:x.families,population:x.population,mfyCount:x.mfyCount,avgPerMfy:x.mfyCount?x.families/x.mfyCount:0}));
 const result={ok:true,agg:{n:a.n,population:a.population,men:a.men,women:a.women,mehnatYosh:a.mehnatYosh,ishsizlar:a.ishsizlar,ishsizlikRate:a.mehnatYosh?a.ishsizlar/a.mehnatYosh*100:0,ijtimoiyReestr,nafaqa,kreditBor,yangiKreditEhtiyoji:a.yangiKreditEhtiyoji,subsidiyaEhtiyoji:a.subsidiyaEhtiyoji,tadbirkorBor:a.tadbirkorBor,kengaytirishIstagi:a.kengaytirishIstagi,kasbHunarIstagi:a.kasbHunarIstagi,uyjoyYetarli,nogironShaxs:a.nogironShaxs,nogironBola:a.nogironBola,yolgizKeksa:a.yolgizKeksa,incomeDist,expenseAvg:a.n?a.expenseTotal/a.n:0,employment,ageBands,malumoti,oilaTarkibi,mulkShakli,uyjoyHujjatlari,internet,tabiiyGaz,ichimlikSuvi,elektr,appliances,livestock,topProblems:top_(topP),topNeeds:top_(topN),indicators:{totalFamilies:a.n,totalPopulation:a.population,unemployment:a.ishsizlar,socialRegistry:ijtimoiyReestr.Ha||0,creditNeed:a.yangiKreditEhtiyoji,subsidyNeed:a.subsidiyaEhtiyoji,entrepreneurs:a.tadbirkorBor},auditStats:{totalRows:a.n,filledTuman:a.n,filledMahalla:a.n,filledKocha:a.n},criticalStats:{unemployed:a.ishsizlar,socialRegistry:ijtimoiyReestr.Ha||0,creditNeed:a.yangiKreditEhtiyoji,subsidyNeed:a.subsidiyaEhtiyoji}},geo:{rows:geoRows},coverage,filters:f,generatedAt:new Date().toISOString()};
 cachePutJson_(key,result,300);return result;
}
function actionMeta_(){const sh=sheet_(),n=Math.max(0,sh.getLastRow()-1);if(!n)return{ok:true,totalFamilies:0,tumans:[],mahallas:[],kochas:[],tree:{}};const rows=sh.getRange(2,2,n,3).getDisplayValues(),ts={},ms={},ks={},tree={};rows.forEach(r=>{const t=clean_(r[0]),m=clean_(r[1]),k=clean_(r[2]);if(t){ts[t]=1;tree[t]=tree[t]||{}}if(m){ms[m]=1;if(t)tree[t][m]=tree[t][m]||{}}if(k){ks[k]=1;if(t&&m)tree[t][m][k]=1}});return{ok:true,totalFamilies:n,tumans:Object.keys(ts).sort(),mahallas:Object.keys(ms).sort(),kochas:Object.keys(ks).sort(),tree,generatedAt:new Date().toISOString()};}
function actionFamilies_(e){const sh=sheet_(),p=e.parameter||{},page=Math.max(1,Number(p.page||1)),pageSize=Math.min(MAX_PAGE_SIZE,Math.max(1,Number(p.pageSize||DEFAULT_PAGE_SIZE))),q=clean_(p.q).toLowerCase(),t=clean_(p.tuman),m=clean_(p.mahalla),k=clean_(p.kocha),n=Math.max(0,sh.getLastRow()-1),rows=n?sh.getRange(2,1,n,9).getDisplayValues():[],out=[];rows.forEach((r,i)=>{if(!clean_(r[1]))return;if(t&&clean_(r[1])!==t)return;if(m&&clean_(r[2])!==m)return;if(k&&clean_(r[3])!==k)return;if(q&&![r[5],r[1],r[2],r[3],r[4]].join(' ').toLowerCase().indexOf(q)<0)return;out.push({_sheetRow:i+2,tuman:r[1]||'',mahalla:r[2]||'',kocha:r[3]||'',uy_raqami:r[4]||'',boshliq_fio:r[5]||'',tugilgan_sana:r[6]||'',jinsi:r[7]||'',telefon:r[8]||''})});const total=out.length,start=(page-1)*pageSize;return{ok:true,page,pageSize,totalPages:Math.ceil(total/pageSize),total,records:out.slice(start,start+pageSize),generatedAt:new Date().toISOString()};}
function rowToFamily_(row,rowNo){const r={_sheetRow:rowNo,_timestamp:row[0]||''};for(let i=0;i<FIELD_KEYS.length;i++)r[FIELD_KEYS[i]]=row[i+1]??'';r.mahalla_original=r.mahalla||'';r.kocha_original=r.kocha||'';r.masul_fio=row[183]??'';return r;}
function actionFamily_(e){const no=Number((e.parameter||{}).row||0),sh=sheet_();if(no<2)return{ok:false,error:'row parametri kerak'};if(no>sh.getLastRow())return{ok:false,error:'Bunday Sheet qatori mavjud emas'};return{ok:true,record:rowToFamily_(sh.getRange(no,1,1,sh.getLastColumn()).getDisplayValues()[0],no),generatedAt:new Date().toISOString()};}
function doGet(e){try{const a=String((e&&e.parameter&&e.parameter.action)||'stats').toLowerCase();let r;if(a==='stats')r=actionStats_(e);else if(a==='meta')r=actionMeta_();else if(a==='families')r=actionFamilies_(e);else if(a==='family')r=actionFamily_(e);else if(a==='check'){const sh=sheet_();r={ok:true,sheet:sh.getName(),rows:Math.max(0,sh.getLastRow()-1),columns:sh.getLastColumn(),fieldKeys:FIELD_KEYS.length,status:'OK'}}else r={ok:false,error:'Noma\'lum action: '+a};return out_(r,e)}catch(err){return out_({ok:false,error:String(err&&err.message||err),stack:String(err&&err.stack||'')},e)}}
function testAll(){const sh=sheet_();Logger.log('Sheet='+sh.getName());Logger.log('Rows='+Math.max(0,sh.getLastRow()-1));Logger.log('Columns='+sh.getLastColumn());Logger.log('FIELD_KEYS='+FIELD_KEYS.length);Logger.log(JSON.stringify(actionStats_({parameter:{}})));Logger.log(JSON.stringify(actionMeta_()));}
