const fs=require('fs'),path=require('path');
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbw3rorMRH3NEldVetbqix8rIac6TPTy1Cz8_DoFAcFJ84MmwAB36DsSFEpAELklCBZA/exec';
const cache=new Map(),inflight=new Map(),TTL=300000,PAGE_SIZE=1000;
function urlFor(action,p={}){const u=new URL(APPS_SCRIPT_URL);u.searchParams.set('action',action);for(const[k,v]of Object.entries(p))if(v!==undefined&&v!==null&&String(v)!=='')u.searchParams.set(k,String(v));u.searchParams.set('_',Date.now().toString());return u}
async function callApps(action,params={}){const key=action+JSON.stringify(params),hit=cache.get(key);if(hit&&Date.now()-hit.at<TTL)return hit.data;if(inflight.has(key))return inflight.get(key);const promise=(async()=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);try{const r=await fetch(urlFor(action,params),{redirect:'follow',headers:{accept:'application/json,text/plain,*/*'},signal:c.signal});const text=await r.text();if(!r.ok)throw new Error('Apps Script HTTP '+r.status+': '+text.slice(0,300));let d;try{d=JSON.parse(text)}catch(_){const m=text.match(/^\s*[A-Za-z_$][\w$\.]*\((.*)\)\s*;?\s*$/s);if(!m)throw new Error('Apps Script javobi JSON emas');d=JSON.parse(m[1])}if(!d||d.ok===false)throw new Error(d?.error||'Apps Script xatolik qaytardi');cache.set(key,{at:Date.now(),data:d});return d}finally{clearTimeout(t);inflight.delete(key)}})();inflight.set(key,promise);return promise}
async function fetchAllFamilies(params={}){const first=await callApps('families',{...params,page:1,pageSize:PAGE_SIZE});const total=Number(first.total||0),ps=Number(first.pageSize||PAGE_SIZE);let rows=Array.isArray(first.rows)?first.rows:(Array.isArray(first.records)?first.records:[]);const pages=Math.max(1,Math.ceil(total/ps));for(let p=2;p<=pages;p+=6){const batch=[];for(let q=p;q<Math.min(p+6,pages+1);q++)batch.push(callApps('families',{...params,page:q,pageSize:ps}));const parts=await Promise.all(batch);parts.forEach(x=>{rows=rows.concat(Array.isArray(x.rows)?x.rows:(Array.isArray(x.records)?x.records:[]))})}return{ok:true,total:total||rows.length,totalPages:pages,page:1,pageSize:ps,records:rows,data:rows}}
function statsFallback(e){return{ok:true,degraded:true,source:'fallback',error:e||'',agg:{n:21113,population:108305,mehnatYosh:87856,ishsizlar:14396,ishsizlikRate:16.38,ijtimoiyReestr:{Ha:2980},employment:{},ageBands:{},topProblems:[],topNeeds:[]},geo:{rows:[]},coverage:[],filters:{},generatedAt:new Date().toISOString()}}
function metaFrom(rows){const t=new Set(),m=new Set(),k=new Set(),tree={};for(const r of rows){const tv=String(r.tuman||'').trim(),mv=String(r.mahalla||'').trim(),kv=String(r.kocha||'').trim();if(tv){t.add(tv);tree[tv]??={mahallalar:{}};if(mv){m.add(mv);tree[tv].mahallalar[mv]??={kochalar:{}};if(kv){k.add(kv);tree[tv].mahallalar[mv].kochalar[kv]=true}}}if(mv)m.add(mv);if(kv)k.add(kv)}return{ok:true,rows:rows.length,totalFamilies:rows.length,tumans:[...t].sort(),mahallalar:[...m].sort(),kochas:[...k].sort(),tree,generatedAt:new Date().toISOString()}}
function metaFallback(e){return{ok:true,degraded:true,error:e||'',source:'fallback',totalFamilies:21113,tumans:[],mahallalar:[],kochas:[],tree:{},generatedAt:new Date().toISOString()}}
function normalize(d){if(!d?.agg)return d;const a=d.agg,p=Math.max(0,Number(a.population)||0),m=Math.max(0,Math.min(Number(a.mehnatYosh)||0,p)),i=Math.max(0,Math.min(Number(a.ishsizlar)||0,m||p));a.mehnatYosh=m;a.ishsizlar=i;a.ishsizlikRate=m?i/m*100:0;return d}
function json(res,status,d){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=60, stale-while-revalidate=300');res.end(JSON.stringify(d))}
module.exports=async function(req,res){const u=new URL(req.url||'/', 'https://vercel.local'),p=u.pathname;try{
if(u.searchParams.get('view')==='dashboard'){try{let html=fs.readFileSync(path.join(process.cwd(),'public','live-dashboard.html'),'utf8');const inject=`<script>(async()=>{try{async function pg(n){const r=await fetch('/api/families?page='+n+'&pageSize=1000&_='+Date.now(),{cache:'no-store'});const j=await r.json();if(j.ok===false)throw new Error(j.error||'API error');return{rows:Array.isArray(j.rows)?j.rows:(Array.isArray(j.records)?j.records:(Array.isArray(j.data)?j.data:[])),total:Number(j.total||0),ps:Number(j.pageSize||1000)}}const f=await pg(1),all=f.rows.slice(),pages=Math.max(1,Math.ceil(f.total/f.ps));for(let i=2;i<=pages;i+=6){const b=[];for(let n=i;n<Math.min(i+6,pages+1);n++)b.push(pg(n));(await Promise.all(b)).forEach(x=>all.push(...x.rows))}if(Array.isArray(window.FAMILIES)){window.FAMILIES.length=0;all.forEach(x=>window.FAMILIES.push(x))}if(typeof window.renderAll==='function')window.renderAll();}catch(e){console.warn('Full family load failed',e)}})();</script>`;html=html.replace('</body>',inject+'</body>');res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(html)}catch(e){return json(res,500,{ok:false,error:'Dashboard HTML: '+e.message})}}
if(p==='/api/health')return json(res,200,{ok:true,service:'surxondaryo-live-dashboard',timestamp:new Date().toISOString()});
if(p==='/api/stats'){try{return json(res,200,normalize(await callApps('stats',{tuman:u.searchParams.get('tuman')||'',mahalla:u.searchParams.get('mahalla')||'',kocha:u.searchParams.get('kocha')||''})))}catch(e){return json(res,200,statsFallback(e.message))}}
if(p==='/api/families'){try{const q={};for(const k of['q','tuman','mahalla','kocha']){const v=u.searchParams.get(k);if(v)q[k]=v}if(u.searchParams.get('all')==='1')return json(res,200,await fetchAllFamilies(q));const page=Math.max(1,Number(u.searchParams.get('page')||1)),pageSize=Math.min(PAGE_SIZE,Math.max(1,Number(u.searchParams.get('pageSize')||PAGE_SIZE)));return json(res,200,await callApps('families',{...q,page,pageSize}))}catch(e){return json(res,200,{ok:true,degraded:true,error:e.message,rows:[],records:[],data:[],total:0,totalPages:1,page:1,pageSize:PAGE_SIZE})}}
if(p==='/api/meta'){try{return json(res,200,metaFrom((await fetchAllFamilies({})).records))}catch(e){return json(res,200,metaFallback(e.message))}}
const m=p.match(/^\/api\/family\/(\d+)$/);if(m)return json(res,200,await callApps('family',{row:m[1]}));return json(res,404,{ok:false,error:'API endpoint topilmadi'});}catch(e){return json(res,200,statsFallback(e.message))}};
